.TH manila 7 2022-10-19 GNU

.SH NAME
   /\\\\/\\\\  /\\\\  /\\\\  /\\\\ /\\\\ /\\\\ /\\\\
  //  V  \\//  \\//  \\// /// /// ///  \\
 // /\\_/\\ V /\\ V /\\ V /// /// /_V /\\ \\
 V_/     \\_/``\\_/  \\_/ V_/ V_____/``\\_\\

.SH SYNOPSIS
Manuel Nila

.SH DESCRIPTION
I like to build things that help people build things

.SH SEE ALSO

.BR https://manic.so
