.TH manila 7 2022-10-19 GNU

.SH NAME
   /\\\\/\\\\  /\\\\  /\\\\  /\\\\ /\\\\ /\\\\ /\\\\
  //  V  \\//  \\//  \\// /// /// ///  \\
 // /\\_/\\ V /\\ V /\\ V /// /// /_V /\\ \\
 V_/     \\_/``\\_/  \\_/ V_/ V_____/``\\_\\

.SH SYNOPSIS
Manuel Nila - Programmer, Creator, and Artist.

.SH DESCRIPTION
Hello! I'm Manuel Nila. I build things. Hire me :)

.SH SEE ALSO

.BR https://manila.me
